### ISSUE TITLE
Roadmap to first version

### ISSUE THREAD

**Issue by ijsnow** [storj-thirdparty/uplink-rust#11]
I see a branch with progress being made. If there were a roadmap with a list of features/tasks remaining I’d help chip in if possible. I’d like to use this in a project of mine!

**Comment by ifraixedes** [comment]
Hi @ijsnow, 

Here Ivan. I'm mostly the only one working on the idiomatic Rust Uplink bindings, despite, I'm not a very experienced Rust developer.

The same branch keeps up to date on [the list of things to be implemented which are listed in the README of the crates folder](https://github.com/storj-thirdparty/uplink-rust/tree/uplink-first-version/uplink#development-plan-and-status).

Without counting a bunch of end-to-end tests that I'd like to implement, the only missing parts to be implemented are the Edge things, which aren't only a few and they shouldn't require much time. You will see that the _project_ is still not marked as done, that's because I'm currently working on it in this branch https://github.com/storj-thirdparty/uplink-rust/tree/if/project

I've implemented the project, but I've been reviewing a few things that I wanted to see if there was a better way for dealing with them, however, I pushed them back until having everything it's implemented because it's related to how to better deal with raw pointers and their "lifetimes", and that's what I'm currently working on.

This binding isn't in the Storj roadmap nor one that's currently considered to be maintained in tasks scheduled in the sprints; I'm working on it during some time that the company grants to employees to work on some related projects, the time isn't a lot but it should be good to finish it before end of May (no considering the end-to-end tests) and to be honest, I should have already finished, but, I prioritized some sprints tasks over the allotted time to work on this.

__My plan__ (this is my voice, not Storj's voice) is to have an alpha release, once I implement the missing parts, without having almost any of those end-to-end tests; then have a beta when the tests are implemented, and perhaps a production-ready once I know that at least some Rust project uses the bindings, however, keep it below `v1.0.0` until at least a few production Rust projects confirm that the crate is usable and quite stable.

If you'd like to contribute to something that's great. I think that it would be more difficult to work on the small number o missing parts because they are only a few and because of the internal changes that may be doing (commented above), however, the public API shouldn't change, hence writing some of the end-to-end tests would help a lot.

Let me know your thoughts and if you want to write some end-to-end tests, in that case, we can discuss a bit about them.

**Comment by ijsnow** [comment]
I could get some end to end tests set up. What features do you think are ready for testing? I suppose the biggest question would be how we'd handle the Storj side. Do you all have a process for doing running a satellite or nodes for web e2e tests?

Also, it's cool that you get this allotted time! (Shameless plug, I saw the senior FE position yesterday and applied :P. The project I want to use it in is definitely a side project.)

**Comment by ifraixedes** [comment]
> What features do you think are ready for testing?

All the tests listed in the [README](https://github.com/storj-thirdparty/uplink-rust/tree/uplink-first-version/uplink#development-plan-and-status) under _Integration tests > Access Grant_ should be feasible using the current state of the branch `uplink-first-version`.

On the other hand, I could merge the _project_ implementation into `uplink-first-version` branch, and then the _Integration tests > Project_ should also be feasible. I don't expect that the refactoring that I'm doing and mentioned in my previous comment will affect them.

>  I suppose the biggest question would be how we'd handle the Storj side. Do you all have a process for doing running a satellite or nodes for web e2e tests?

Currently, we have to mechanism to start a "full" storj system on local:

* [storj-sim](https://github.com/storj/storj/wiki/Test-network)
* [storj-up](https://github.com/storj/up)

The former is more robust because it exists for a long time. We also use it for some end-to-end tests that our CI runs. The other one is fancier, it runs the third-party dependencies (database, Redis, etc.) at the expense that is quite new so it's less battle-tested.

Feel free to poke with one of them if you wish.

You could use any of the production systems through a free account. I don't expect that these tests will require that much data to be stored nor much bandwidth so the free account limits should be enough.

At this stage, I cannot say how we are going to run these tests as part of the CI process of these crates. So far, the repository has Github Actions setup and they run a single test for the `uplink-sys` that use the production system. I didn't set it up but I think that I can discuss internally with other people what CI system would like to use in this repository and how to run all the tests, once we have more than the existing ones.

In case you don't already know, the `uplink` crate has some unit tests, and I'd like to run them through the CI on every PR and each time that `main` beach is updated. You can actually see that this is a task that appears in the README linked above in _implemenation > development plan and status > general_.

**Comment by ifraixedes** [comment]
@ijsnow I've merged the _project_ implementation into the `uplink-first-version` branch.

I'll follow up with the mentioned internal refactoring in another branch
